### ISSUE TITLE
Recognizes inner attributes as outer attributes throws formatting errors for alphabetizing attributes

### ISSUE THREAD

**Issue by jotchon** [drewbrokke/SublimeLinter-contrib-check-source-formatting#1]
**Example:** 
<a class="${logo_css_class}" href="${site_default_url}" **title="<@language_format arguments="${site_name}" key="go-to-x" />"**></a>

**Thrown Error**:  Alphabetize the attributes

**Possible cause**: Under title attribute, the attributes for language_format element is recognized as attributes in the <a> element.

**Comment by drewbrokke** [comment]
Hey @jotchon, thanks for filing this issue.  Do you know if this also occurs when using the `check-source-formatting` command line tool? Or is it just when using this editor plugin? If it also happens on the command line, then it will have to be fixed at the `check-source-formatting` project instead of here. 

See this repo: https://github.com/liferay/liferay-frontend-source-formatter

**Comment by drewbrokke** [comment]
Closing based on our discussion.  New issue filed here: https://github.com/liferay/liferay-frontend-source-formatter/issues/25.  Thanks @jotchon.
